// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func WavesBackground() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n  body {\n    /* background-color: #5461C3 */\n    background-image: linear-gradient(to right, #3678f9, #5461C3)\n  }\n\n  .box {\n    position: fixed;\n    top: 0;\n    transform: rotate(40deg);\n    left: 0;\n  }\n\n  .wave {\n    position: absolute;\n    opacity: .5;\n    width: 1500px;\n    height: 1300px;\n    margin-left: -150px;\n    margin-top: -250px;\n    border-radius: 43%;\n  }\n\n  @keyframes rotate {\n    from {\n      transform: rotate(0deg);\n    }\n\n    from {\n      transform: rotate(360deg);\n    }\n  }\n\n  .wave.-one {\n    animation: rotate 10000ms infinite linear;\n    background: #1c766c;\n  }\n\n  .wave.-two {\n    animation: rotate 6000ms infinite linear;\n    background: #5dffff;\n  }\n\n  .star {\n    background-image: url('./kuz.png');\n  }\n</style><div class=\"box\"><div class=\"wave -one\"></div><div class=\"wave -two\"></div><!-- <div class='star'></div> --></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
