// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func positionClassName(pos int) string {
	switch pos {
	case 0:
		return "top-0 left-1/2 -translate-x-1/2"
	case 1:
		return "top-1/4 right-0"
	case 2:
		return "bottom-1/4 right-0"
	case 3:
		return "bottom-0 left-1/2 -translate-x-1/2"
	case 4:
		return "bottom-1/4 left-0"
	case 5:
		return "top-1/4 left-0"
	}

	return ""
}

func WordGameStuff() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = WordGame([]string{}, []string{"a", "e", "i", "o", "u", "m"}, "n").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func WordGame(possibleWords []string, letters []string, mainLetter string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"bg-gray-100 min-h-screen p-8\"><div class=\"max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8\"><!-- Left side - Letters --><div class=\"flex flex-col items-center gap-4\"><div class=\"relative w-72 h-72\"><!-- Center circle --><div class=\"absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-full bg-slate-500 flex items-center justify-center\"><span class=\"text-3xl font-bold text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(mainLetter)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/views/wordgame.templ`, Line: 34, Col: 63}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div><!-- Surrounding circles -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i, letter := range letters {
			var templ_7745c5c3_Var4 = []any{"absolute w-20 h-20 rounded-full bg-gray-200 flex items-center justify-center", positionClassName(i)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var4...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var4).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/views/wordgame.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"><span class=\"text-2xl font-bold text-foreground\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(letter)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/views/wordgame.templ`, Line: 41, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"flex gap-4 mt-4\"><button class=\"px-4 py-2 border border-gray-300 rounded-md text-sm font-medium bg-white hover:bg-gray-50\">Apagar</button> <button class=\"px-4 py-2 bg-teal-500 text-white rounded-md text-sm font-medium hover:bg-teal-600\">Confirmar</button></div></div><!-- Right side - Words --><div class=\"space-y-6\"><div class=\"space-y-2\"><div class=\"flex items-center justify-between\"><h2 class=\"text-lg font-semibold\">Iniciante</h2><span class=\"text-sm text-gray-500\">0/85</span></div><div class=\"w-full bg-gray-200 rounded-full h-2\"><div class=\"bg-teal-500 h-2 rounded-full\" style=\"width: 0%\"></div></div></div><div><h3 class=\"text-sm font-medium mb-4\">Palavras já encontradas</h3><div class=\"grid grid-cols-2 gap-3\"><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div><div class=\"px-3 py-2 border rounded-md text-sm text-gray-500\">4 letras</div></div></div><button class=\"w-full px-4 py-2 border border-gray-300 rounded-md text-sm font-medium bg-white hover:bg-gray-50\">Encerrar partida</button></div></div></body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
